namespace ImmichUploaderApp.Services;

public static class Loc
{
    public static string Language { get; set; } = "fi";

    public static readonly (string Code, string Name)[] SupportedLanguages =
    {
        ("fi", "Suomi"),
        ("en", "English"),
        ("sv", "Svenska"),
        ("de", "Deutsch"),
    };

    public static string T(string key, params object[] args)
    {
        var template = Resolve(key);
        return args.Length == 0 ? template : string.Format(template, args);
    }

    private static string Resolve(string key)
    {
        if (Strings.TryGetValue(Language, out var dict) && dict.TryGetValue(key, out var value)) return value;
        if (Strings["en"].TryGetValue(key, out var fallback)) return fallback;
        return key;
    }

    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
    {
        ["fi"] = new()
        {
            ["app.name"] = "Immich Uploader",
            ["status.idle"] = "Ajan tasalla",
            ["status.stopped"] = "Pysähdyksissä",
            ["status.paused"] = "Tauolla",
            ["status.queued"] = "{0} tiedostoa jonossa",
            ["status.uploading"] = "Ladataan: {0}",
            ["status.startFailed"] = "Käynnistys epäonnistui: {0}",
            ["tray.statusFormat"] = "Tila: {0}",
            ["tray.pause"] = "Keskeytä lataukset",
            ["tray.resume"] = "Jatka latauksia",
            ["tray.openServer"] = "Avaa Immich",
            ["tray.settings"] = "Asetukset...",
            ["tray.viewLog"] = "Näytä loki",
            ["tray.exit"] = "Lopeta",
            ["tray.logOpenFailed"] = "Lokin avaaminen epäonnistui: {0}",
            ["panel.settingsButton"] = "Asetukset",
            ["panel.loading"] = "Ladataan...",
            ["panel.recentHeader"] = "VIIMEISIMMÄT",
            ["panel.noUploads"] = "Ei vielä latauksia.",
            ["panel.storageHeader"] = "TALLENNUSTILA",
            ["panel.storageUnavailable"] = "Tallennustilan tietoja ei saatavilla",
            ["panel.storageUsed"] = "{0} / {1} käytetty",
            ["time.justNow"] = "juuri nyt",
            ["time.minutesAgo"] = "{0} min sitten",
            ["time.hoursAgo"] = "{0} t sitten",
            ["time.daysAgo"] = "{0} pv sitten",
            ["settings.title"] = "Immich Uploader – asetukset",
            ["settings.serverUrlLabel"] = "Immich-palvelimen osoite (esim. https://immich.example.com/api)",
            ["settings.apiKeyLabel"] = "API-avain",
            ["settings.showKey"] = "Näytä",
            ["settings.testConnection"] = "Testaa yhteys",
            ["settings.testing"] = "Testataan...",
            ["settings.testOk"] = "Yhteys OK ({0} albumia).",
            ["settings.testError"] = "Virhe: {0}",
            ["settings.testMissingFields"] = "Anna palvelimen osoite ja API-avain.",
            ["settings.albumNameLabel"] = "Albumin nimi (valinnainen)",
            ["settings.deviceNameLabel"] = "Laitteen nimi",
            ["settings.watchedFoldersLabel"] = "Tarkkailtavat kansiot",
            ["settings.addFolder"] = "Lisää kansio...",
            ["settings.removeSelected"] = "Poista valittu",
            ["settings.folderAlreadyListed"] = "Kansio on jo listalla.",
            ["settings.chooseFolderDialog"] = "Valitse tarkkailtava kansio",
            ["settings.exclusionsLabel"] = "Poissuljettavat alikansiot (poista valinta kansioilta joita EI ladata):",
            ["settings.startWithWindows"] = "Käynnistä Windowsin käynnistyessä",
            ["settings.themeLabel"] = "Ulkoasu",
            ["settings.themeSystem"] = "Järjestelmän mukaan",
            ["settings.themeLight"] = "Vaalea",
            ["settings.themeDark"] = "Tumma",
            ["settings.languageLabel"] = "Kieli",
            ["settings.save"] = "Tallenna",
            ["settings.cancel"] = "Peruuta",
            ["settings.missingRequiredFields"] = "Palvelimen osoite ja API-avain ovat pakollisia.",
            ["settings.noFolders"] = "Lisää ainakin yksi tarkkailtava kansio.",
            ["settings.updatesLabel"] = "Päivitykset",
            ["settings.currentVersion"] = "Käytössä oleva versio: {0}",
            ["settings.checkForUpdates"] = "Tarkista päivitykset",
            ["settings.checkingForUpdates"] = "Tarkistetaan...",
            ["settings.upToDate"] = "Sinulla on uusin versio.",
            ["settings.updateAvailable"] = "Uusi versio saatavilla: {0}",
            ["settings.updateCheckFailed"] = "Päivitysten tarkistus epäonnistui: {0}",
            ["settings.downloadAndInstall"] = "Lataa ja asenna",
            ["settings.downloadingUpdate"] = "Ladataan päivitystä... {0} %",
            ["settings.updateDownloadFailed"] = "Päivityksen lataus epäonnistui: {0}",
            ["settings.updateLaunchBlocked"] = "Windows esti asennusohjelman käynnistyksen (usein virustorjunnan väärä hälytys allekirjoittamattomalle ohjelmalle). Avataan julkaisusivu selaimeen, josta voit ladata sen manuaalisesti.",
            ["settings.updateInstallConfirm"] = "Asennusohjelma käynnistetään ja sovellus suljetaan hetkeksi asennuksen ajaksi. Jatketaanko?",
            ["settings.tabGeneral"] = "Yleiset",
            ["settings.tabServer"] = "Palvelin",
            ["settings.tabFolders"] = "Kansiot",
        },
        ["en"] = new()
        {
            ["app.name"] = "Immich Uploader",
            ["status.idle"] = "Up to date",
            ["status.stopped"] = "Stopped",
            ["status.paused"] = "Paused",
            ["status.queued"] = "{0} files queued",
            ["status.uploading"] = "Uploading: {0}",
            ["status.startFailed"] = "Startup failed: {0}",
            ["tray.statusFormat"] = "Status: {0}",
            ["tray.pause"] = "Pause uploads",
            ["tray.resume"] = "Resume uploads",
            ["tray.openServer"] = "Open Immich",
            ["tray.settings"] = "Settings...",
            ["tray.viewLog"] = "View log",
            ["tray.exit"] = "Exit",
            ["tray.logOpenFailed"] = "Failed to open log: {0}",
            ["panel.settingsButton"] = "Settings",
            ["panel.loading"] = "Loading...",
            ["panel.recentHeader"] = "RECENT",
            ["panel.noUploads"] = "No uploads yet.",
            ["panel.storageHeader"] = "STORAGE",
            ["panel.storageUnavailable"] = "Storage information unavailable",
            ["panel.storageUsed"] = "{0} / {1} used",
            ["time.justNow"] = "just now",
            ["time.minutesAgo"] = "{0} min ago",
            ["time.hoursAgo"] = "{0} h ago",
            ["time.daysAgo"] = "{0} d ago",
            ["settings.title"] = "Immich Uploader – Settings",
            ["settings.serverUrlLabel"] = "Immich server address (e.g. https://immich.example.com/api)",
            ["settings.apiKeyLabel"] = "API key",
            ["settings.showKey"] = "Show",
            ["settings.testConnection"] = "Test connection",
            ["settings.testing"] = "Testing...",
            ["settings.testOk"] = "Connection OK ({0} albums).",
            ["settings.testError"] = "Error: {0}",
            ["settings.testMissingFields"] = "Enter a server address and an API key.",
            ["settings.albumNameLabel"] = "Album name (optional)",
            ["settings.deviceNameLabel"] = "Device name",
            ["settings.watchedFoldersLabel"] = "Watched folders",
            ["settings.addFolder"] = "Add folder...",
            ["settings.removeSelected"] = "Remove selected",
            ["settings.folderAlreadyListed"] = "That folder is already in the list.",
            ["settings.chooseFolderDialog"] = "Choose a folder to watch",
            ["settings.exclusionsLabel"] = "Excluded subfolders (uncheck folders that should NOT be uploaded):",
            ["settings.startWithWindows"] = "Start with Windows",
            ["settings.themeLabel"] = "Appearance",
            ["settings.themeSystem"] = "Match system",
            ["settings.themeLight"] = "Light",
            ["settings.themeDark"] = "Dark",
            ["settings.languageLabel"] = "Language",
            ["settings.save"] = "Save",
            ["settings.cancel"] = "Cancel",
            ["settings.missingRequiredFields"] = "Server address and API key are required.",
            ["settings.noFolders"] = "Add at least one folder to watch.",
            ["settings.updatesLabel"] = "Updates",
            ["settings.currentVersion"] = "Current version: {0}",
            ["settings.checkForUpdates"] = "Check for updates",
            ["settings.checkingForUpdates"] = "Checking...",
            ["settings.upToDate"] = "You have the latest version.",
            ["settings.updateAvailable"] = "New version available: {0}",
            ["settings.updateCheckFailed"] = "Update check failed: {0}",
            ["settings.downloadAndInstall"] = "Download and install",
            ["settings.downloadingUpdate"] = "Downloading update... {0} %",
            ["settings.updateDownloadFailed"] = "Update download failed: {0}",
            ["settings.updateLaunchBlocked"] = "Windows blocked the installer from starting (often an antivirus false positive for unsigned software). Opening the release page in your browser so you can download it manually.",
            ["settings.updateInstallConfirm"] = "The installer will launch and the app will close briefly while it updates. Continue?",
            ["settings.tabGeneral"] = "General",
            ["settings.tabServer"] = "Server",
            ["settings.tabFolders"] = "Folders",
        },
        ["sv"] = new()
        {
            ["app.name"] = "Immich Uploader",
            ["status.idle"] = "Uppdaterad",
            ["status.stopped"] = "Stoppad",
            ["status.paused"] = "Pausad",
            ["status.queued"] = "{0} filer i kö",
            ["status.uploading"] = "Laddar upp: {0}",
            ["status.startFailed"] = "Start misslyckades: {0}",
            ["tray.statusFormat"] = "Status: {0}",
            ["tray.pause"] = "Pausa uppladdningar",
            ["tray.resume"] = "Återuppta uppladdningar",
            ["tray.openServer"] = "Öppna Immich",
            ["tray.settings"] = "Inställningar...",
            ["tray.viewLog"] = "Visa logg",
            ["tray.exit"] = "Avsluta",
            ["tray.logOpenFailed"] = "Kunde inte öppna loggen: {0}",
            ["panel.settingsButton"] = "Inställningar",
            ["panel.loading"] = "Läser in...",
            ["panel.recentHeader"] = "SENASTE",
            ["panel.noUploads"] = "Inga uppladdningar än.",
            ["panel.storageHeader"] = "LAGRINGSUTRYMME",
            ["panel.storageUnavailable"] = "Lagringsinformation ej tillgänglig",
            ["panel.storageUsed"] = "{0} / {1} använt",
            ["time.justNow"] = "just nu",
            ["time.minutesAgo"] = "{0} min sedan",
            ["time.hoursAgo"] = "{0} tim sedan",
            ["time.daysAgo"] = "{0} dgr sedan",
            ["settings.title"] = "Immich Uploader – Inställningar",
            ["settings.serverUrlLabel"] = "Immich-serverns adress (t.ex. https://immich.example.com/api)",
            ["settings.apiKeyLabel"] = "API-nyckel",
            ["settings.showKey"] = "Visa",
            ["settings.testConnection"] = "Testa anslutning",
            ["settings.testing"] = "Testar...",
            ["settings.testOk"] = "Anslutning OK ({0} album).",
            ["settings.testError"] = "Fel: {0}",
            ["settings.testMissingFields"] = "Ange serverns adress och API-nyckel.",
            ["settings.albumNameLabel"] = "Albumnamn (valfritt)",
            ["settings.deviceNameLabel"] = "Enhetens namn",
            ["settings.watchedFoldersLabel"] = "Bevakade mappar",
            ["settings.addFolder"] = "Lägg till mapp...",
            ["settings.removeSelected"] = "Ta bort markerad",
            ["settings.folderAlreadyListed"] = "Mappen finns redan i listan.",
            ["settings.chooseFolderDialog"] = "Välj en mapp att bevaka",
            ["settings.exclusionsLabel"] = "Uteslutna undermappar (avmarkera mappar som INTE ska laddas upp):",
            ["settings.startWithWindows"] = "Starta när Windows startar",
            ["settings.themeLabel"] = "Utseende",
            ["settings.themeSystem"] = "Följ systemet",
            ["settings.themeLight"] = "Ljust",
            ["settings.themeDark"] = "Mörkt",
            ["settings.languageLabel"] = "Språk",
            ["settings.save"] = "Spara",
            ["settings.cancel"] = "Avbryt",
            ["settings.missingRequiredFields"] = "Serverns adress och API-nyckel krävs.",
            ["settings.noFolders"] = "Lägg till minst en mapp att bevaka.",
            ["settings.updatesLabel"] = "Uppdateringar",
            ["settings.currentVersion"] = "Aktuell version: {0}",
            ["settings.checkForUpdates"] = "Sök efter uppdateringar",
            ["settings.checkingForUpdates"] = "Söker...",
            ["settings.upToDate"] = "Du har den senaste versionen.",
            ["settings.updateAvailable"] = "Ny version tillgänglig: {0}",
            ["settings.updateCheckFailed"] = "Uppdateringskontrollen misslyckades: {0}",
            ["settings.downloadAndInstall"] = "Ladda ner och installera",
            ["settings.downloadingUpdate"] = "Laddar ner uppdatering... {0} %",
            ["settings.updateDownloadFailed"] = "Nedladdning av uppdatering misslyckades: {0}",
            ["settings.updateLaunchBlocked"] = "Windows blockerade installationsprogrammet från att starta (ofta ett falskt virusvarningslarm för osignerad programvara). Öppnar utgivningssidan i webbläsaren så att du kan ladda ner den manuellt.",
            ["settings.updateInstallConfirm"] = "Installationsprogrammet startar och appen stängs kort under installationen. Fortsätta?",
            ["settings.tabGeneral"] = "Allmänt",
            ["settings.tabServer"] = "Server",
            ["settings.tabFolders"] = "Mappar",
        },
        ["de"] = new()
        {
            ["app.name"] = "Immich Uploader",
            ["status.idle"] = "Aktuell",
            ["status.stopped"] = "Gestoppt",
            ["status.paused"] = "Pausiert",
            ["status.queued"] = "{0} Dateien in Warteschlange",
            ["status.uploading"] = "Wird hochgeladen: {0}",
            ["status.startFailed"] = "Start fehlgeschlagen: {0}",
            ["tray.statusFormat"] = "Status: {0}",
            ["tray.pause"] = "Uploads pausieren",
            ["tray.resume"] = "Uploads fortsetzen",
            ["tray.openServer"] = "Immich öffnen",
            ["tray.settings"] = "Einstellungen...",
            ["tray.viewLog"] = "Protokoll anzeigen",
            ["tray.exit"] = "Beenden",
            ["tray.logOpenFailed"] = "Protokoll konnte nicht geöffnet werden: {0}",
            ["panel.settingsButton"] = "Einstellungen",
            ["panel.loading"] = "Wird geladen...",
            ["panel.recentHeader"] = "ZULETZT",
            ["panel.noUploads"] = "Noch keine Uploads.",
            ["panel.storageHeader"] = "SPEICHERPLATZ",
            ["panel.storageUnavailable"] = "Speicherinformationen nicht verfügbar",
            ["panel.storageUsed"] = "{0} / {1} belegt",
            ["time.justNow"] = "gerade eben",
            ["time.minutesAgo"] = "vor {0} Min.",
            ["time.hoursAgo"] = "vor {0} Std.",
            ["time.daysAgo"] = "vor {0} Tg.",
            ["settings.title"] = "Immich Uploader – Einstellungen",
            ["settings.serverUrlLabel"] = "Immich-Serveradresse (z. B. https://immich.example.com/api)",
            ["settings.apiKeyLabel"] = "API-Schlüssel",
            ["settings.showKey"] = "Anzeigen",
            ["settings.testConnection"] = "Verbindung testen",
            ["settings.testing"] = "Wird getestet...",
            ["settings.testOk"] = "Verbindung OK ({0} Alben).",
            ["settings.testError"] = "Fehler: {0}",
            ["settings.testMissingFields"] = "Bitte Serveradresse und API-Schlüssel angeben.",
            ["settings.albumNameLabel"] = "Albumname (optional)",
            ["settings.deviceNameLabel"] = "Gerätename",
            ["settings.watchedFoldersLabel"] = "Überwachte Ordner",
            ["settings.addFolder"] = "Ordner hinzufügen...",
            ["settings.removeSelected"] = "Auswahl entfernen",
            ["settings.folderAlreadyListed"] = "Dieser Ordner ist bereits in der Liste.",
            ["settings.chooseFolderDialog"] = "Zu überwachenden Ordner auswählen",
            ["settings.exclusionsLabel"] = "Ausgeschlossene Unterordner (Häkchen entfernen für Ordner, die NICHT hochgeladen werden sollen):",
            ["settings.startWithWindows"] = "Mit Windows starten",
            ["settings.themeLabel"] = "Erscheinungsbild",
            ["settings.themeSystem"] = "Systemeinstellung verwenden",
            ["settings.themeLight"] = "Hell",
            ["settings.themeDark"] = "Dunkel",
            ["settings.languageLabel"] = "Sprache",
            ["settings.save"] = "Speichern",
            ["settings.cancel"] = "Abbrechen",
            ["settings.missingRequiredFields"] = "Serveradresse und API-Schlüssel sind erforderlich.",
            ["settings.noFolders"] = "Fügen Sie mindestens einen zu überwachenden Ordner hinzu.",
            ["settings.updatesLabel"] = "Updates",
            ["settings.currentVersion"] = "Aktuelle Version: {0}",
            ["settings.checkForUpdates"] = "Nach Updates suchen",
            ["settings.checkingForUpdates"] = "Wird geprüft...",
            ["settings.upToDate"] = "Sie haben die neueste Version.",
            ["settings.updateAvailable"] = "Neue Version verfügbar: {0}",
            ["settings.updateCheckFailed"] = "Update-Prüfung fehlgeschlagen: {0}",
            ["settings.downloadAndInstall"] = "Herunterladen und installieren",
            ["settings.downloadingUpdate"] = "Update wird heruntergeladen... {0} %",
            ["settings.updateDownloadFailed"] = "Update-Download fehlgeschlagen: {0}",
            ["settings.updateLaunchBlocked"] = "Windows hat den Start des Installationsprogramms blockiert (oft ein Fehlalarm des Virenschutzes bei unsignierter Software). Die Release-Seite wird im Browser geöffnet, damit Sie sie manuell herunterladen können.",
            ["settings.updateInstallConfirm"] = "Das Installationsprogramm wird gestartet und die App wird kurz für die Installation geschlossen. Fortfahren?",
            ["settings.tabGeneral"] = "Allgemein",
            ["settings.tabServer"] = "Server",
            ["settings.tabFolders"] = "Ordner",
        },
    };
}
